PUT http://localhost:3001/api/users/62098af72a9dc940b6eac69b HTTP/1.1
content-type: application/json

{
  "email": "wSD",
  "hin": "ASD",
  "password": "ASD",
  "firstName": "FRANK",
  "lastName": "SMITH",
  "role": "Patient",
  "associated_users": [] 
}